#### Data Engineering Numpy (Array Processing)


#### 1. Create a NumPy array with 10 random integers between 0 and 100.

In [2]:
import numpy as np

array = np.random.randint(0, 101, size=10)

print(array)


[75 56 57 29  4 48 98 78 21 72]


#### 2. Use the np.where() function to create a new array with the same shape as the previous one, where values less than 50 are replaced with -1 and values greater than or equal to 50 are replaced with 1.

In [4]:

array = np.random.randint(0, 101, size=10)

print("Original array:")
print(array)

new_array = np.where(array < 50, -1, 1)

print("\nNew array:")
print(new_array)


Original array:
[85 27 10 59 20 42 27 43 75  8]

New array:
[ 1 -1 -1  1 -1 -1 -1 -1  1 -1]


#### 3. Calculate the mean, median, and standard deviation of the original array.

In [5]:

arr = np.random.randint(0, 101, size=10)

print("Original array:")
print(arr)

mean = np.mean(arr)

median = np.median(arr)

std_dev = np.std(arr)

print("\nMean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Original array:
[46 34 35 97 26 18  0 68 69 73]

Mean: 46.6
Median: 40.5
Standard Deviation: 28.11476480428033


#### 4. Create a boolean array that is True where the values in the original array are even, and False otherwise.

In [6]:

array = np.random.randint(0, 101, size=10)

print("Original array:")
print(array)

boolean_array = array % 2 == 0

print("\nBoolean array:")
print(boolean_array)


Original array:
[48  1  3 67 82 63 31  8 69 68]

Boolean array:
[ True False False False  True False False  True False  True]


#### 5. Sort the original array in ascending order.

In [7]:
array = np.array([9, 5, 2, 7, 1])

sorted_array = np.sort(array)

sorted_array


array([1, 2, 5, 7, 9])

#### sort the original array in descending order

In [8]:

array = np.array([9, 5, 2, 7, 1])

sorted_array = np.sort(array)[::-1]

sorted_array


array([9, 7, 5, 2, 1])

#### 6. Find the unique values in the original array.

In [9]:
array = np.array([1, 7, 3, 2, 1, 4, 5, 4, 6])

unique_values = np.unique(array)

print(unique_values)


[1 2 3 4 5 6 7]


#### 7. Use the np.in1d() function to create a boolean array indicating which elements of the original array are also present in a new array with 5 random integers between 0 and 100.

In [11]:
original_array = np.array([1, 2, 3, 4, 5])

new_array = np.random.randint(0, 100, size=5)

is_in_new_array = np.in1d(original_array, new_array)

print(is_in_new_array)


[False False  True False False]


##### 8. Save the original array to a text file named "my_array.txt" using the np.savetxt() function.


In [12]:
original_array = np.array([1, 2, 3, 4, 5])

np.savetxt("my_array.txt", original_array)

print("Array saved to my_array.txt")


Array saved to my_array.txt
