#### Data Engineering Numpy (Universal Array Function)


###  Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.exp()function to compute the exponential of each element in the array.
 

In [8]:
import numpy as np

array = np.random.rand(3, 3)

print("Original array:")
print(array)

# Compute the exponential of each element using np.exp()
exp_array = np.exp(array)
print("\nExponential array:")
print(exp_array)

l=np.log(exp_array)
print("\nreal output:")
print(l)


Original array:
[[0.3763387  0.09774242 0.3039286 ]
 [0.67807017 0.47833673 0.97163219]
 [0.06614454 0.09874208 0.32737961]]

Exponential array:
[[1.45694052 1.10267872 1.3551723 ]
 [1.97007216 1.61338866 2.64225359]
 [1.06838113 1.10378157 1.38732802]]

real output:
[[0.3763387  0.09774242 0.3039286 ]
 [0.67807017 0.47833673 0.97163219]
 [0.06614454 0.09874208 0.32737961]]


In [4]:
import numpy as np

# Create a NumPy array with shape (3,3) filled with random numbers
array = np.random.rand(3, 3)

print("Original array:")
print(array)

# Compute the exponential of each element using np.exp()
exp_array = np.exp(array)

print("\nExponential array:")
print(exp_array)


Original array:
[[0.28689244 0.59152226 0.64136135]
 [0.00816488 0.94821248 0.60676607]
 [0.26921429 0.883269   0.58945472]]

Exponential array:
[[1.3322809  1.80673664 1.89906441]
 [1.0081983  2.58109177 1.83448918]
 [1.30893561 2.41879385 1.80300501]]


In [19]:
array = np.random.rand(3, 3)

print("Original array:")
print(array)

l=np.log(array)
print("\nreal output:")
print(l)


Original array:
[[0.3761148  0.57832797 0.26629548]
 [0.80178887 0.59534271 0.7769275 ]
 [0.69327806 0.62397523 0.92964582]]

real output:
[[-0.97786087 -0.54761415 -1.32314877]
 [-0.22090997 -0.51861806 -0.25240824]
 [-0.36632411 -0.4716446  -0.07295161]]


#### Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.sin() function to compute the sine of each element in the array.

In [9]:

array = np.random.rand(4, 4)

print("Original array:")
print(array)

# Compute the sine of each element using np.sin()
sin_array = np.sin(array)

print("\nSine array:")
print(sin_array)


Original array:
[[0.92515107 0.76012693 0.76199672 0.78077796]
 [0.31865317 0.82188891 0.8961148  0.25124776]
 [0.0470808  0.5918266  0.1729326  0.12039506]
 [0.11981694 0.07310346 0.71190143 0.60707053]]

Sine array:
[[0.79871167 0.68901344 0.69036737 0.70383227]
 [0.31328781 0.73243318 0.78090593 0.24861274]
 [0.04706341 0.55787789 0.17207194 0.12010442]
 [0.11953046 0.07303836 0.65327456 0.57046387]]


#### Create a NumPy array with shape (2,2) and fill it with random numbers. Use the np.sqrt() function to compute the square root of each element in the array

In [11]:

array = np.random.rand(2, 2)

print("Original array:")
print(array)

sqrt_array = np.sqrt(array)

print("\nSquare root array:")
print(sqrt_array)



Original array:
[[0.85046559 0.26917402]
 [0.63507346 0.22070047]]

Square root array:
[[0.92220691 0.51881984]
 [0.79691497 0.46978768]]


#####  Create a NumPy array with shape (6,6) and fill it with random numbers. Use the np.floor() function to round down each element in the array to the nearest integer.

In [13]:
array = np.random.rand(6, 6)
print(array)

sqrt_array = np.round(array)

print("\nround array:")
print(sqrt_array)

[[0.93439309 0.97825423 0.75480681 0.07889318 0.9224487  0.5639127 ]
 [0.50033113 0.85991241 0.62370073 0.27092997 0.03705882 0.81918437]
 [0.76233653 0.1110419  0.69138969 0.27423749 0.86487513 0.94051082]
 [0.51894589 0.98472498 0.61156884 0.23523947 0.50233465 0.49900749]
 [0.63631163 0.84312161 0.5717473  0.93314778 0.79215603 0.12455208]
 [0.65774538 0.65591323 0.48365499 0.96972478 0.31870519 0.86783789]]

Square root array:
[[1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 0. 0. 1.]
 [1. 0. 1. 0. 1. 1.]
 [1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 0. 1. 0. 1.]]


In [15]:
array = np.random.rand(2, 2)

print("Original array:")
print(array)

sqrt_array = np.floor(array)

print("\nfloor array:")
print(sqrt_array)

Original array:
[[0.00162712 0.31832575]
 [0.33791944 0.24071688]]

floor array:
[[0. 0.]
 [0. 0.]]


#### Create a NumPy array with shape (3,3) and fill it with random numbers. Use the np.abs() function to compute the absolute value of each element in the array

In [17]:
array = np.random.rand(3, 3)

print("Original array:")
print(array)

absolute_value = np.abs(array)

print("\nabsolute valuearray:")
print(absolute_value)

Original array:
[[0.09538988 0.59610827 0.34941367]
 [0.2708909  0.412675   0.0983937 ]
 [0.28496064 0.67222865 0.47234577]]

absolute valuearray:
[[0.09538988 0.59610827 0.34941367]
 [0.2708909  0.412675   0.0983937 ]
 [0.28496064 0.67222865 0.47234577]]


#### Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.power() function to raise each element in the array to the power of 2

In [18]:

array = np.random.rand(4, 4)

print("Original array:")
print(array)

power_array = np.power(array, 2)

print("\nRaised to the power of 2 array:")
print(power_array)


Original array:
[[0.19294842 0.22150073 0.7694583  0.75070124]
 [0.39509886 0.70133156 0.63212083 0.06254406]
 [0.79587173 0.07596452 0.91556109 0.19666012]
 [0.92189114 0.97302284 0.53173818 0.32490608]]

Raised to the power of 2 array:
[[0.03722909 0.04906257 0.59206608 0.56355235]
 [0.15610311 0.49186596 0.39957675 0.00391176]
 [0.6334118  0.00577061 0.83825211 0.0386752 ]
 [0.84988328 0.94677346 0.28274549 0.10556396]]


#### Create a NumPy array with 5 random integers between 1 and 10. Use the maximum function to find the largest element in the array.

In [20]:

array = np.random.randint(1, 11, size=5)

print("Array of random integers:")
print(array)

largest_element = np.max(array)

print("\nLargest element in the array:", largest_element)


Array of random integers:
[4 4 8 3 9]

Largest element in the array: 9


#### Create a NumPy array with 10 random floating-point numbers between 0 and 1. Use the round function to round each element to the nearest integer

In [21]:

array = np.random.rand(10)

print("Original array:")
print(array)

rounded_array = np.round(array)

print("\nRounded array:")
print(rounded_array)


Original array:
[0.94610213 0.90493862 0.85817549 0.77427303 0.4898077  0.70795107
 0.66320097 0.474339   0.82682387 0.26748899]

Rounded array:
[1. 1. 1. 1. 0. 1. 1. 0. 1. 0.]


#### Create a NumPy array with 7 random integers between 1 and 100. Use the argmax function to find the index of the largest element in the array.


In [25]:
array = np.random.randint(1,101,7)

print("Original array:")
print(array)

largest_element = np.argmax(array)

print("\nlargest element:")
print(largest_element)

Original array:
[ 8 11 54 63 25 97 24]

largest element:
5


#### Create two NumPy arrays with the same shape, each filled with random integers between 1 and 10  Use the add function to add the two arrays together element-wise.

In [26]:

array1 = np.random.randint(1, 11, size=(4, 4))
array2 = np.random.randint(1, 11, size=(4, 4))

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

result_array = np.add(array1, array2)

print("\nResult array:")
print(result_array)



Array 1:
[[8 5 8 7]
 [6 6 1 9]
 [7 7 9 4]
 [6 1 2 2]]

Array 2:
[[ 9  9  8  9]
 [ 4  2  3  7]
 [10  1  2 10]
 [ 9  5  9  1]]

Result array:
[[17 14 16 16]
 [10  8  4 16]
 [17  8 11 14]
 [15  6 11  3]]


#### Create a NumPy array with 12 random integers between 0 and 100. Use the clip function to limit the values in the array to a range between 10 and 90

In [27]:

array = np.random.randint(0, 101, size=12)

print("Original array:")
print(array)

clipped_array = np.clip(array, 10, 90)

print("\nClipped array:")
print(clipped_array)


Original array:
[  2  25 100  40   7  77   6  83  52  67  98  75]

Clipped array:
[10 25 90 40 10 77 10 83 52 67 90 75]
